const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const { GoogleGenerativeAI, SchemaType } = require('@google/generative-ai');
const swaggerSpec = require('./swagger');

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

// Serve Swagger UI using CDN (Vercel serverless compatible)
app.get('/api-docs', (req, res) => {
    res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PulseIdea API Documentation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css" />
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = () => {
            window.ui = SwaggerUIBundle({
                spec: ${JSON.stringify(swaggerSpec)},
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>
    `);
});

app.use(cors());
app.use(express.json());

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * @swagger
 * /api/refine:
 *   post:
 *     summary: Refine a raw idea into a detailed specification and diagram.
 *     description: Sends a prompt to Google Gemini to generate a refined description and a valid Mermaid diagram code.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - prompt
 *             properties:
 *               prompt:
 *                 type: string
 *                 description: The raw idea to refine. Maximum 500 characters.
 *                 maxLength: 500
 *                 example: "A to-do list app for astronauts"
 *     responses:
 *       200:
 *         description: Successful refinement.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 improvedIdea:
 *                   type: string
 *                   description: The detailed specification generated by AI.
 *                 diagram:
 *                   type: string
 *                   description: The Mermaid.js diagram code.
 *       400:
 *         description: Bad Request. Prompt missing or exceeds 500 characters.
 *       500:
 *         description: Server error or AI failure.
 */
app.post('/api/refine', async (req, res) => {
    try {
        const { prompt } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'Prompt is required' });
        }

        if (prompt.length > 500) {
            return res.status(400).json({ error: 'Prompt exceeds execution limit of 500 characters' });
        }

        const schema = {
            description: "Refinement response",
            type: SchemaType.OBJECT,
            properties: {
                improvedIdea: {
                    type: SchemaType.STRING,
                    description: "Detailed specification in Markdown",
                    nullable: false,
                },
                diagram: {
                    type: SchemaType.STRING,
                    description: "Valid Mermaid.js graph code",
                    nullable: false,
                },
            },
            required: ["improvedIdea", "diagram"],
        };

        const model = genAI.getGenerativeModel({
            model: "gemini-2.5-flash",
            systemInstruction: `You are an expert software architect and product manager. Your task is to take a raw app idea and refine it into a professional, detailed specification and a Mermaid.js diagram.

PART 1 - IMPROVED IDEA RULES:
- Use Markdown: # for title, ## for sections, - for bullets, **bold** for emphasis.
- Include: Executive Summary, Key Features, Target Audience, Tech Stack.

PART 2 - MERMAID DIAGRAM RULES:
1. Start with "graph TD;".
2. Use semicolons (;) at the end of every line.
3. Wrap ALL node labels in double quotes. Example: A["User Visits Site"].
4. Connect nodes with arrows (-->).
5. Ensure the diagram describes the core user flow or architecture.
6. Create 5-15 nodes.
7. NEVER leave this field empty.`,
            generationConfig: {
                responseMimeType: "application/json",
                responseSchema: schema,
            }
        });

        const promptTemplate = `Refine this app idea: ${prompt}`;

        const result = await model.generateContent(promptTemplate);
        const response = await result.response;
        const text = response.text();

        let parsedData;
        try {
            parsedData = JSON.parse(text);

            // Additional validation: ensure diagram is not empty
            if (!parsedData.diagram || parsedData.diagram.trim() === '') {
                console.warn('Warning: AI returned empty diagram, using fallback');
                parsedData.diagram = `graph TD;
A["Start"] --> B["Process"];
B --> C{"Decision?"};
C -- "Yes" --> D["Action 1"];
C -- "No" --> E["Action 2"];
D --> F["End"];
E --> F;`;
            }
        } catch (e) {
            console.error("JSON Parse Error on string:", jsonStr);
            // Fallback: If JSON is broken, return the raw text as the idea and a default diagram
            parsedData = {
                improvedIdea: text,
                diagram: `graph TD;
A["Start"] --> B["Process"];
B --> C{"Decision?"};
C -- "Yes" --> D["Action 1"];
C -- "No" --> E["Action 2"];
D --> F["End"];
E --> F;`
            };
        }

        res.json(parsedData);


    } catch (error) {
        console.error('Error processing request:', error);
        res.status(500).json({
            error: 'Failed to refine prompt',
            message: error.message
        });
    }
});




const server = app.listen(port, () => {
    console.log(`Backend server running on http://localhost:${port}`);
});

